repository_path = "."
env_filename = ".env"
env_keys = []
file_extensions = [
    "js",
    "ts",
    "jsx",
    "tsx",
    "py",
    "rb",
    "php",
    "java",
    "go",
    "rs",
    "cpp",
    "c",
    "cs",
    "yaml",
    "yml",
    "json",
    "xml",
    "md",
    "txt",
]
ignore_patterns = [
    "node_modules",
    ".git",
    "target",
    "dist",
    "build",
    ".next",
    "coverage",
    ".nyc_output",
    "logs",
    "*.log",
    ".DS_Store",
    "Thumbs.db",
]
enable_web_scan = false
